name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://live.adapt.to

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm

    - run: npm install
    - run: npm run lint
    - run: npm run test:unit
    - run: npm run build
      env:
        VITE_SERVER_URL: ${{ vars.VITE_SERVER_URL }}
        VITE_SCHEDULE_DATA_URL: ${{ vars.VITE_SCHEDULE_DATA_URL }}
        VITE_QUERY_INDEX_URL: ${{ vars.VITE_QUERY_INDEX_URL }}
        VITE_LAMAPOLL_URL: ${{ vars.VITE_LAMAPOLL_URL }}
        VITE_DEBUG_MODE: ${{ vars.VITE_DEBUG_MODE }}
        VITE_SHOW_DEBUG_MODE: ${{ vars.VITE_SHOW_DEBUG_MODE }}
        VITE_SHUTDOWN_PAGE: ${{ vars.VITE_SHUTDOWN_PAGE }}
        VITE_WARNING_NOTICE: ${{ vars.VITE_WARNING_NOTICE }}
        VITE_ALLOW_QAENTRY_ANONYMOUS: ${{ vars.VITE_ALLOW_QAENTRY_ANONYMOUS }}

    - name: Copy to Site
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      env:
        API_TOKEN_GITHUB: ${{ secrets.GH_SITE_DEPLOY_PAT }}
      with:
        source-directory: dist
        destination-repository-username: adaptto-live
        destination-repository-name: adaptto-live.github.io
        destination-github-username: ${{ secrets.GH_SITE_DEPLOY_USERNAME }}
        user-email: ${{ secrets.GH_SITE_DEPLOY_EMAIL }}
        user-name: ${{ secrets.GH_SITE_DEPLOY_NAME }}
        target-branch: main
        commit-message: deploy application
